### ISSUE TITLE
Check if custom fonts have been loaded

### ISSUE THREAD

**Issue by mariojankovic** [arapl3y/vue-blotter#1]
Hey, first of all this is really cool! Thanks for making a vue port of blotter.
Second, there's been some discussion on how to enable custom fonts that are not yet loaded. Initially, with your plugin the fonts fall back to the first alternative (e.g. 'Custom Font', Arial, sans-serif where it obviously renders Arial first as it hasn't yet loaded the 'Custom Font' in question). What I propose is a simple check like this:
```
// Instantiate global instance of Blotter class
document.fonts.ready.then(function () {
  this.initBlotter();
})
```

Bear in mind that I haven't been able to test this so I haven't done a PR. I'm seeing an error when trying to build the plugin anew via vue-sfc-rollup.

In any case, here's an official example from the creator of Blotter on how to render blotter as soon as the custom font has loaded: https://codepen.io/bradleygriffith/pen/wOrewY

Cheers!

**Comment by arapl3y** [comment]
Hi Mario,

Thanks a lot for the feedback!  I can definitely look into this soon. If you manage to get it up and running in the mean time feel free to make a PR.

If you come across any other issues, please let me know :)

Cheers,
Alex

**Comment by mariojankovic** [comment]
Awesome! I'll try and see if I'm able to come up with something to run build in the meantime. 

**UPDATE:** I was able to build but wrapping `initBlotter()` inside `document.fonts.ready` didn't do anything. So instead, I did a simple v-if on my `vue-blotter` like this:

```
<vue-blotter v-if="fontsLoaded" ... />

...

data () {
  return {
	fontsLoaded: false
  }
}
mounted () {
  document.fonts.ready.then(() => {
    this.fontsLoaded = true
  })
}
```

So I guess there's no need to check for fonts.loaded by default since that would render some vue-blotter instances only after all fonts have been loaded, even though you could have been using a system font for blotter itself.

Alternatively you could check for individual fonts by specifying family I guess, something like this:
```
if (document.fonts.check(`1em ${this.family}`)) { // Init blotter }
```

But again, not sure if this needs to be part of the core itself since you could do several other check with v-if anyway.

Again, thanks for this wonderful vue port of blotter. :)
Cheers.
